### ISSUE TITLE
Crawler

### ISSUE THREAD

**Issue by tlenclos** [tlenclos/joli-mapstr#22]
https://github.com/tlenclos/joli-mapstr/pull/21

## TODO

- [x] Script de crawl
- [x] Github action
- [x] Sauvegarder le JSON et l'utiliser dans l'app
- [x] Appeler l'action github à interval régulier
